"""empty message

Revision ID: f4b077906aea
Revises: e8acb28247a6
Create Date: 2025-12-05 20:31:33.516169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b077906aea'
down_revision = 'e8acb28247a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_constraint('people_age_key', type_='unique')

    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.drop_constraint('planeta_clima_key', type_='unique')
        batch_op.drop_constraint('planeta_diametro_key', type_='unique')
        batch_op.drop_constraint('planeta_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.create_unique_constraint('planeta_name_key', ['name'])
        batch_op.create_unique_constraint('planeta_diametro_key', ['diametro'])
        batch_op.create_unique_constraint('planeta_clima_key', ['clima'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_unique_constraint('people_age_key', ['age'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
